# Generated by Django 5.0.13 on 2025-11-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='id_mascota',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_veterinario',
            new_name='veterinario',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_dueno',
            new_name='dueno',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='id_mascota',
            new_name='mascota',
        ),
    ]
